name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Run go lint for racing
      run: cd racing && go vet .

    - name: Run go lint for service
      run: cd sports && go vet .

    - name: Run go lint for api
      run: cd api && go vet .

    - name: Unit Tests for racing
      run: cd racing/db && go test -v ./...

    - name: Unit Tests for sports
      run: cd sports/db && go test -v ./...
